version: '3.5'

services:

    #EarnApp Configuration
    earnapp:
        image: fazalfarhan01/earnapp:lite
        restart: always
        environment:
            - EARNAPP_UUID=sdk-node-f854215136ca47b194196ab4887b4658
        networks:
            default:
                ipv4_address: 172.106.0.10
    #end of EarnApp Configuration

    #HoneyGain Configuration
    honeygain:
        image: honeygain/honeygain
        command: -tou-accept -email 'a1102086061@gmail.com' -pass 'a19921214' -device EarningMachine
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.20
    #end of HoneyGain Configuration

    #Peer2Profit Configuration
    peer2profit:
        image: peer2profit/peer2profit_x86_64:latest
        restart: always
        environment:
            - P2P_EMAIL='YOUR_PEER2PROFIT_EMAIL_ADDRESS
        networks:
            default:
                ipv4_address: 172.106.0.30
    #end of Peer2Profit Configuration

    #PacketStream Configuration
    psclient:
        image: packetstream/psclient:latest
        restart: always
        environment:
            - CID=5JLa
        networks:
            default:
                ipv4_address: 172.106.0.40

    pswatchtower:
        depends_on:
            - psclient
        image: containrrr/watchtower
        command: --cleanup --include-stopped --revive-stopped --interval 60 earning-machine_psclient_1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.41
    #end of PacketStream Configuration

    #Pawns Configuration
    pawns:
        image: iproyal/pawns-cli:latest
        command: -email='YOUR_PAWNS_EMAIL_ADDRESS' -password='YOUR_PAWNS_USER_PASSWORD' -device-name=EarningMachine -accept-tos
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.50
    #end of Pawns Configuration
    
    #Bitping Configuration
    bitping:
        image: bitping/bitping-node:latest
        restart: always
        volumes:
            - ./data/bitping:/root/.bitping
        networks:
            default:
                ipv4_address: 172.106.0.60
    #end of Bitping Configuration

    #TraffMonetizer Configuration
    traffmonetizer:
        image: traffmonetizer/cli:latest
        restart: always
        command: start accept --token YOUR_TRAFFMONETIZER_TOKEN
        networks:
            default:
                ipv4_address: 172.106.0.70
    #end of TraffMonetizer Configuration

    #Repocket Configuration
    repocket:
        image: repocket/repocket:latest
        restart: always
        environment:
           - RP_EMAIL=YOUR_REPOCKET_EMAIL_ADDRESS
           - RP_PASSWORD=YOUR_REPOCKET_USER_PASSWORD
        networks:
            default:
                ipv4_address: 172.106.0.80
    #end of Repocket Configuration

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16